name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          uv pip install -r requirements/lint.txt

      - name: Run linting
        run: |
          make lint

  tests:
    name: Tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv pip install -r requirements/ci.txt

      - name: Run tests
        run: |
          make test

      - name: Build distribution and test installation
        shell: bash
        run: |
          make build
          uv pip install scipeds@$(find dist -name 'scipeds*.whl') --no-deps --force-reinstall
          python -c "import scipeds"
          uv pip install scipeds@$(find dist -name 'scipeds*.tar.gz') --no-deps --force-reinstall
          python -c "import scipeds"
